image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache curl python python-dev py-pip
  - pip install --upgrade pip
  - pip install awscli
  - $(aws ecr get-login --no-include-email --region eu-west-1)
  - cd aws-ecs

build-env:
  stage: build
  script:
    # Nginx Matomo
    - docker build -f nginx.Dockerfile -t matomonginx .
    - docker tag matomonginx:latest 111111111111.dkr.ecr.eu-west-1.amazonaws.com/matomonginx:latest
    - docker push 111111111111.dkr.ecr.eu-west-1.amazonaws.com/matomonginx:latest
    # Matomo
    - docker build -f matomo.Dockerfile -t matomo .
    - docker tag matomo:latest 111111111111.dkr.ecr.eu-west-1.amazonaws.com/matomo:latest
    - docker push 111111111111.dkr.ecr.eu-west-1.amazonaws.com/matomo:latest
  tags:
    - example-runner
    - docker-privileged

deploy:
  stage: deploy
  script:
    - aws ecs update-service --cluster $CLUSTER_NAME --service matomo_service --force-new-deployment --desired-count 1 --region eu-west-1
  tags:
    - example-runner
    - docker-privileged